
services:
  - type: web
    name: renta-estimacion-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app"
    envVars:
      - key: OPENAI_API_KEY
        value: REEMPLAZAR_POR_TU_CLAVE
